[package]
name = "plygui-macros"
version = "0.0.1"
authors = ["Serhii Plyhun <snuk188@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "~0.15"
quote = "~0.6"
proc-macro2 = "~0.4"
heck = "~0.3"
